DROP TABLE IF EXISTS chat;
CREATE TABLE chat(id INT NOT NULL AUTO_INCREMENT,
  fromuser INT NOT NULL,
  touser INT NOT NULL,
  subject VARCHAR(78) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id));
