DROP TABLE IF EXISTS message;
CREATE TABLE message(id INT NOT NULL AUTO_INCREMENT,
  chat_id INT NOT NULL,
  user_id INT NOT NULL,
  text TEXT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_customer FOREIGN KEY (chat_id)
  REFERENCES chat(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE)